#!/bin/bash

apt-get update -qq

apt-get install -y chromium-browser

# Controlla se chromedriver è installato e compatibile
if ! command -v chromedriver &> /dev/null; then
    echo "Chromedriver non trovato, scarico manualmente"

    CHROME_VER=$(chromium-browser --version | grep -oP '\d+\.\d+\.\d+')
    CHROMEDRIVER_VER=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VER")
    wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VER}/chromedriver_linux64.zip"
    unzip -qq chromedriver_linux64.zip -d /usr/local/bin/
    chmod +x /usr/local/bin/chromedriver
    rm chromedriver_linux64.zip
else
    echo "Chromedriver già presente"
fi
